// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sample NewsFeed API
This is a sample server for a News Feed.


    Schemes:
      http
    Host: localhost
    BasePath: /news-api/v1
    Version: 1.0.0
    Contact: API Support<support@example.com> http://www.example.com/support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
