swagger: '2.0'
info:
  title: Sample NewsFeed API
  description: This is a sample server for a News Feed.
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  version: 1.0.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    $ref: ./paths/test.yml
definitions:
  test:
    $ref: ./definitions/test.yml

basePath: /news-api/v1